# Generated by Django 6.0.1 on 2026-02-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
        ("users", "0003_payment"),
    ]

    operations = []
