# Generated by Django 6.0.1 on 2026-02-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_merge_0002_payments_0003_payment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payments",
        ),
    ]
