# Generated by Django 6.0.1 on 2026-02-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Укажите цену курса",
                max_digits=10,
                verbose_name="Цена",
            ),
        ),
    ]
