# Generated by Django 6.0.1 on 2026-02-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор продукта в Stripe",
                max_length=255,
                verbose_name="Stripe Product ID",
            ),
        ),
    ]
